#In this notebook we are going to cover the fundamental concepts of Tensors using TensorFlow

Outline:
* Intro to Tensors
* Getting info from Tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function (way to speed up Python functions
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try


# Introduction to Tensors

In [18]:
# Import Tensorflow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [19]:
# Create our first tensor with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [20]:
# Check the number of dimensions of a tensor (ndim - num of dimensions)
scalar.ndim

0

In [21]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [22]:
# Check the dimension of vector
vector.ndim

1

In [23]:
# Create a matrix (More than 1 dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [24]:
# Check dimension of matrix
matrix.ndim

2

In [25]:
#specify datatype in matrix
another_matrix = tf.constant([[10.,7.],[3.,2.],[4.,6.]], dtype=tf.float16) # specify data type with dtype parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 4.,  6.]], dtype=float16)>

In [26]:
# What is the ndim of another_matrix?
another_matrix.ndim

2

In [27]:
# Create a tensor
tensor = tf.constant([[[1,2,3],[2,3,4]],[[3,4,5],[6,7,8]],[[7,8,9],[8,9,10]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  3,  4]],

       [[ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 7,  8,  9],
        [ 8,  9, 10]]])>

In [28]:
# How many dims are in the tensor
tensor.ndim

3

What we've created so far
* Scalar - single number
* Vector - a number with direction (e.g. wind speed and direction)
* Matrix - a 2 dimensional array of numbers
* tensor - an n-dimensional array of numbers (where n can be any number)

### Creating tensors with `tf.variable()`

In [29]:
# create the same tensor as above with tf.variable()
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7])>)

In [30]:
# Lets change one of the elements in changable tensor
# changeable_tensor[0] = 7
# changable_tensor

In [31]:
# try .assign
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [32]:
#try to change in the unchangeable tensor
unchangeable_tensor[0] = 7

TypeError: ignored

In [33]:
unchangeable_tensor[0].assign(7)

AttributeError: ignored

### Creating Random tensors

Random tensors are tensors of some arbitrary size that contains random numbers.


In [34]:
#create 2 random (but the same) tensors
random_tensor1 = tf.random.Generator.from_seed(42) #set seed for reproducability
random_tensor1 = random_tensor1.normal(shape=(3,2))
random_tensor2 = tf.random.Generator.from_seed(42)
random_tensor2 = random_tensor2.normal(shape=(3,2))

# Are they equal?
random_tensor1, random_tensor2, random_tensor1 == random_tensor2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor

In [35]:
#shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesnt impact learning)
not_shuffled = tf.constant([[10,7],[2,5],[4,6],[99,10]])
not_shuffled.ndim

2

In [36]:
not_shuffled

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 4,  6],
       [99, 10]])>

In [37]:
#shuffle the non_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[99, 10],
       [ 4,  6],
       [10,  7],
       [ 2,  5]])>

In [38]:
# global vs operational level seeds
# global will keep the shuffle the same where operational will not
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled,seed=42)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 4,  6],
       [10,  7],
       [99, 10]])>

In [39]:
random1 = tf.constant([[1,2],[2,3],[3,4],[4,5],[5,6]])
random2 = tf.constant([[10,20],[20,30],[30,40],[40,50],[50,60]])
random3 = tf.constant([[100,200],[200,300],[300,400],[400,500],[500,600]])
random4 = tf.constant([[1000,2000],[2000,3000],[3000,4000],[4000,5000],[5000,6000]])
random5 = tf.constant([[10000,20000],[20000,30000],[30000,40000],[40000,50000],[50000,60000]])

In [40]:
# different every time
tf.random.shuffle(random1, seed=44)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 6],
       [1, 2],
       [3, 4],
       [4, 5]])>

In [41]:
tf.random.set_seed(45) # global level random seed
tf.random.shuffle(random2) # operation level random seed

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[10, 20],
       [50, 60],
       [30, 40],
       [40, 50],
       [20, 30]])>

In [42]:
tf.random.set_seed(45)
tf.random.shuffle(random3)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[100, 200],
       [500, 600],
       [300, 400],
       [400, 500],
       [200, 300]])>

In [43]:
tf.random.set_seed(45)
tf.random.shuffle(random2, seed=10)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[20, 30],
       [10, 20],
       [30, 40],
       [50, 60],
       [40, 50]])>

In [44]:
tf.random.set_seed(45)
tf.random.shuffle(random3, seed=10)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[200, 300],
       [100, 200],
       [300, 400],
       [500, 600],
       [400, 500]])>

In [45]:
# the combination of global and operational seed create a consistent shuffle
# global also seems to have a default seed and maintains consistency when within the same version of tensorflow or usercode (see Rule #2)

# https://www.tensorflow.org/api_docs/python/tf/random/set_seed


> 1. If neither the global seed nor the operation seed is set: A randomly picked seed is used for this op.
> 2. If the global seed is set, but the operation seed is not: The system deterministically picks an operation seed in conjunction with the global seed so that it gets a unique random sequence. Within the same version of tensorflow and user code, this sequence is deterministic. However across different versions, this sequence might change. If the code depends on particular seeds to work, specify both global and operation-level seeds explicitly.
> 3. If the operation seed is set, but the global seed is not set: A default global seed and the specified operation seed are used to determine the random sequence.
> 4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

### Other ways to make tensors

In [46]:
# create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [47]:
# create a tensor of all zeros
tf.zeros(shape=(3,4,5))

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

### Turn NumPy arrays into Tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numberical computing)

In [48]:
# you can also turn numpy arrays into tensors
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) # create a numpy array between 1-25
numpy_A
# Matrix or tensor is generally in a capital variable
# non-capital for vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [49]:
A = tf.constant(numpy_A, shape=(2,3,4)) # tensor
B = tf.constant(numpy_A) # vector
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [50]:
A.ndim,B.ndim

(3, 1)

In [51]:
2 * 3 * 4 # must equal the number of elements in numpy array

24

In [52]:
A = tf.constant(numpy_A, shape=(2,2,6)) # tensor
A

<tf.Tensor: shape=(2, 2, 6), dtype=int32, numpy=
array([[[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]],

       [[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]])>

### Getting information from Tensors

* Shape -- *tensor.shape*
* Rank -- *tensor.ndim*
* Axis or Dimension -- *tensor[0], tensor[:,1]*
* Size -- *tf.size(tensor)*

In [53]:
#  Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [54]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [55]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [56]:
2*3*4*5

120

In [57]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor (tf.Tensor type):", tf.size(rank_4_tensor))
print("Total number of elements in our tensor (NumPy):", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor (tf.Tensor type): tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor (NumPy): 120


### Indexing tensors

Tensors can be indexed just like Python lists.

In [58]:
pyList = [1,2,3,4]
pyList[:2]

[1, 2]

In [59]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [60]:
# Get the first element from each dimension except the last
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [61]:
# Get the first element from each dimension except the second to last
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [62]:
# Get the first element from each dimension except the second
rank_4_tensor[:1,:,:1,:1]

<tf.Tensor: shape=(1, 3, 1, 1), dtype=float32, numpy=
array([[[[0.]],

        [[0.]],

        [[0.]]]], dtype=float32)>

In [63]:
# Get the first element from each dimension except the first
rank_4_tensor[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [64]:
#Create a rank 2 tensor that has 2 dimensions
rank_2_tensor = tf.constant([[5,8],[2,7]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [65]:
#get the last item of each row of the rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([8, 7])>

In [66]:
# Add an extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [8]],

       [[2],
        [7]]])>

In [67]:
# Add an extra dimension to our rank 2 tensor
# ... on every previous axis
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [8]],

       [[2],
        [7]]])>

In [68]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[5],
        [8]],

       [[2],
        [7]]])>

In [69]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[5, 8],
        [2, 7]]])>

In [70]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[5, 8]],

       [[2, 7]]])>

In [71]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[5, 8],
       [2, 7]])>

### Manipulating Tensors (tensor operations)

**Basic Operations**
`+`,`-`,`*`,`/`

In [72]:
# you can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [73]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]])>

In [74]:
# Original tensor is changed
tensor = tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [75]:
tensor * 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2000, 1700],
       [1300, 1400]])>

In [76]:
tensor - 100

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-80, -83],
       [-87, -86]])>

In [77]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[2. , 1.7],
       [1.3, 1.4]])>

In [78]:
# We can use the tf built-in functions too (faster on GPU)

tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 170],
       [130, 140]])>

In [79]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

**Matrix multiplication**

In Machine Learning, matrix multiplication is one of the most common tensor operations

matrixmultiplication.xyz


There are 2 rules the Tensors need to fulfil if you are going to multiply them:

1. The inner dimentions must match
2. The resulting tensor has the shape of the outer dimensions


In [80]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]])>

In [81]:
# Matrix multiplication in TensorFlow
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]])>

In [82]:
# Matrix multiplication with Python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]])>

In [83]:
# Practice
test_tensor1 = tf.constant([[1,2,1],[0,1,0],[2,3,4]])
test_tensor2 = tf.constant([[2,5],[6,7],[1,8]])

tf.matmul(test_tensor1,test_tensor2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]])>

In [84]:
# Create a tensor of 3,2
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])

X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [85]:
# Try to multiply with the same shape
tf.matmul(X,Y)

InvalidArgumentError: ignored

In [86]:
X.shape

TensorShape([3, 2])

In [87]:
Y.shape

TensorShape([3, 2])

In [88]:
# [3, 2] [3, 2] The inner dimensions 2 and 3 do not match

In [89]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]])>

In [90]:
# Let's change the shape of Y
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]])>

In [91]:
X.shape, tf.reshape(Y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [92]:
# Try to matrix multiply X by reshaped Y
X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [93]:
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [94]:
# Try changing the shape of X instead of Y

tf.matmul(tf.reshape(X,shape=(2,3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [95]:
tf.reshape(X, shape=(2,3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [96]:
# Can do the same with transpose
# Transpose flips axis where reshape shuffles the elements around
X, tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>)

In [97]:
# Try matrix multiplication with transpose rather than reshape
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

**The Dot Product**

Matrix multiplication is often known as the dot product.
You can perform matrix multiplication using:

* `tf.matmul()`
* `tf.tensordot()`]
* `@`

In [98]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]])>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]])>)

In [99]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]])>

In [100]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])>

In [101]:
#Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]])>

In [102]:
# Notice the different results

In [103]:
# Check the values for Y, reshape Y and transpose Y
print("Normal Y:")
print(Y, "\n")

print("Y reshapes to (2,3):")
print(tf.reshape(Y, shape=(2,3)))

print("Y transposed to (2,3):")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshapes to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32)
Y transposed to (2,3):
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


Generally when performing matrix mult. on two tensors and one of the axes doesn't line up you will transpose rather than reshape one of the tensors to satisfy the matrix multiplication rules

### Change the datatype of a tensor

In [104]:
# Create a new tensor witht he default datatype (float32)
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [105]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [106]:
# Change from float32 to float16 (reduced precision) (Mixed precision)
# 16 bit precision will run faster that 32 bit precision but lose accuracy
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [107]:
#Change from int32 to float32
C = tf.cast(C, dtype=tf.float32)
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

In [108]:
C = tf.cast(C, dtype=tf.float16)
C

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values


In [110]:
# Get the absolute values
D = tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10])>

In [111]:
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10])>

Lets go through the following forms of aggregation

* Get the minimum of a tensor
* Get the maximum of a tensor
* Get the mean of a tensor
* Get the sum of a tensor

In [115]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([ 0, 82, 66, 26,  0, 93, 56, 24, 11,  7, 63, 43, 68, 84, 79, 26,  9,
       84, 89,  6, 82, 63, 73, 90, 12, 85, 54, 98, 77, 82, 70, 78, 82, 67,
       71, 83, 73, 18, 51,  2, 87, 42, 98,  5, 17, 54, 28, 63, 45, 83])>

In [116]:
tf.size(E), E.shape,E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [118]:
# Find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [119]:
np.min(E)

0

In [120]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int32, numpy=98>

In [121]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int32, numpy=54>

In [122]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int32, numpy=2749>

**Exercise:** Find the variance and standard deviation of E tensor

In [126]:
# Find the variance
import tensorflow_probability as tfp
tf.reduce_variance(E)

ModuleNotFoundError: ignored

In [141]:
# Find the variance
# to find the variance we need tensorflow_probability (NOT TRUE, SEE BELOW)
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int32, numpy=951>

In [135]:
# Find the standard deviation
tf.math.reduce_std(E)

TypeError: ignored

In [138]:
# to find the standard deviation, the values must be a dtype of float
# TypeError: Input must be either real or complex. Received integer type <dtype: 'int32'>.
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=30.834715>

In [142]:
# Find the variance using tf instead of tfp
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=950.7796>

###Find the positional maximum and minimum

In [153]:
# Create a new tensor for finding positional Min and Max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [154]:
# Find the positional max
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [155]:
# INdex on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [156]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [158]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [159]:
# Find the positional min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [160]:
# Index on our smallest value position
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [161]:
tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [162]:
# Check for equality
F[tf.argmin(F)] == tf.reduce_min(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

### Squeezing a tensor (removing all single dimensions)

In [167]:
# Create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [168]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [172]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

> https://machinelearningmastery.com/why-one-hot-encode-data-in-machine-learning/


red, green, blue
> 1, 0, 0

> 0, 1, 0

> 0, 0, 1

In [176]:
# Create a list of indeces
some_list = [0,1,2,3] # could be red, green, blue, yellow

# One-Hot encode out list of indices
tf.one_hot(some_list,4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [178]:
# Specify custom values for one-hot encoding
tf.one_hot(some_list,4, on_value="YES", off_value="NO")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'YES', b'NO', b'NO', b'NO'],
       [b'NO', b'YES', b'NO', b'NO'],
       [b'NO', b'NO', b'YES', b'NO'],
       [b'NO', b'NO', b'NO', b'YES']], dtype=object)>

In [180]:
tf.one_hot(some_list,10)

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

### Squaring, log, sq root

In [181]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

In [183]:
# Square the tensor
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])>

In [186]:
# Find sq root (  Will error, method requires non int type)
tf.sqrt(H)

InvalidArgumentError: ignored

In [185]:
# Must cast it to a new dtype
tf.sqrt(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [188]:
# Find the log of H (will error, requires a non int dtype)

tf.math.log(H)

InvalidArgumentError: ignored

In [191]:
# Must cast as a non int dtype
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

Tensorflow interacts very well with NumPy arrays

NumPY - The fundamental package for scientific computing with Python

In [193]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3.,4.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  4., 10.])>

In [194]:
# Method 1: Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  4., 10.]), numpy.ndarray)

In [197]:
# Method 2: Convert tensor J to a NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  4., 10.]), numpy.ndarray)

In [200]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [202]:
# The default types of each are slightly different
numpy_J = tf.constant(np.array([3.,4.,10.])) # float64
tensor_J = tf.constant([3.,4.,10.]) # float32
#Check the datatypes of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)